### ISSUE TITLE
Checkmarks Could Be Improved

### ISSUE THREAD

**Issue by phoney** [uxmstudio/UXMPDFKit#23]
Couple suggestions for the checkboxes. Currently the checkboxes are invisible when not checked and even when checked they don't really look like checkboxes. 

What I suggest is to configure the buttons as toggle buttons. You'll need two images, one for the checked appearance and the other for the unchecked appearance. Set the checked image for the selected state and the unchecked image for the normal state. Add an action method for touchupinside and button.selected = !button.selected. When the selected state is set the checkmark image will appear.

If you felt like it you can easily make a UIButton subclass with that behavior built in and just use that when you're building the checkmark button. This is probably best.

**Comment by pushchris** [comment]
Thanks for the suggestion, I will add it to the queue of improvements. I would suggest not using images but rather doing it all through views. This way it is resolution independent. If you would like to contribute, feel free to fork and submit a pull request.

**Comment by phoney** [comment]
Perhaps unicode characters would work. There are Ballot box with check and Ballot Box characters that might work. There are a few other checkmark characters but I'm not sure what would indicate the unchecked state. This could conceivably be configurable.

I may well do this. It isn't hard. The toggle buttons would also work as part of the radio button implementation.

Is the queue of improvements public? I'm mainly interested in having a working Acroforms implementation.

**Comment by pushchris** [comment]
Unicode could work as well. I posted a page in the wiki with the current [road map](https://github.com/uxmstudio/UXMPDFKit/wiki/Road-Map). Looking to add a few more UI components to the reader on whole, then move towards actually properly implementing annotations and form editing. Currently everything is burned on top of the PDF which while functional, is not really ideal.

**Comment by phoney** [comment]
I'll close this issue since you accepted my pull request.
