### ISSUE TITLE
Initialization from NSData is not supported

### ISSUE THREAD

**Issue by edias** [uxmstudio/UXMPDFKit#31]
At the moment the only initialization possible with the PDFDocument is from an URL string.

I was wondering me if there's any plan to implement a version to support initialization from NSData.

**Comment by pushchris** [comment]
Initialization with NSData is already supported. See the following:
https://github.com/uxmstudio/UXMPDFKit/blob/master/Pod/Classes/Renderer/PDFDocument.swift#L93

**Comment by edias** [comment]
Not on swift-2.3 branch

**Comment by edias** [comment]
Any plans to support NSData on 0.3.0 version?

**Comment by edias** [comment]
hey @pushchris, I'm not able to see digital signature like for example this one just below 

[6697225c-2d55-4792-b338-1761ee5283ac.pdf](https://github.com/uxmstudio/UXMPDFKit/files/680708/6697225c-2d55-4792-b338-1761ee5283ac.pdf)

**Comment by pushchris** [comment]
Could you be a little bit more specific? Are you signing on another app and then loading the document into the reader? This is also a different issue than this thread, so if you wouldn't mind opening a new issue for this that would be appreciated.

**Comment by edias** [comment]
Just moved here https://github.com/uxmstudio/UXMPDFKit/issues/34
