### ISSUE TITLE
Crash when passing nil as a password on PDFDocument creation

### ISSUE THREAD

**Issue by CKzu** [uxmstudio/UXMPDFKit#32]
Hi and first of all thanks for the work!

I encountered an issue while using the library : when I tried to create a PDFDocument instance for a file without a password, my first attempt was to call `PDFDocument(filePath: path, password: nil)`, which caused my app to crash with mysterious error messages.

I managed to fixed it by calling `PDFDocument(filePath: path, password: "")`.

This should be either stated clearly in the docs (maybe I've missed it?) or fixed in the code.

Cheers!

**Comment by pushchris** [comment]
@CKzu that is very strange, the default implementation of PDFDocument without a password (```PDFDocument(filePath: path)```) simply calls ```PDFDocument(filePath: path, password: nil)```. So ```nil``` should not be giving you any issues (in theory). Can you paste the crash log? 

Additionally, you can take a look [here](https://github.com/uxmstudio/UXMPDFKit/blob/master/Pod/Classes/Renderer/CGPDFDocument.swift#L17) at how opening a PDF is handled. The only time it will send you a ```CGPDFDocumentError``` is if the file is encrypted and no password is provided.

**Comment by pushchris** [comment]
I modified the document unlocking logic a littler bit in the latest build. Give it a try, if you are still having issues, feel free to re-open.
