### ISSUE TITLE
Carthage build Error

### ISSUE THREAD

**Issue by OmarCaf** [uxmstudio/UXMPDFKit#33]
Hi, 

I've the following error building from Carthage:
**Dependency "UXMPDFKit" has no shared framework schemes for any of the platforms: iOS**

Thank you in advance,
Omar.

**Comment by pushchris** [comment]
@OmarCaf give the latest build a try. If you are still having issues with it let me know.

**Comment by OmarCaf** [comment]
Hi @pushchris now it's working thank you ;)

**Comment by pushchris** [comment]
@OmarCaf perfect! Let me know if you have any other issues using the framework.
