### ISSUE TITLE
Issues with undoing annotations

### ISSUE THREAD

**Issue by Xorcist77** [uxmstudio/UXMPDFKit#39]
Seems the there is some weirdness with undoing annotations.

Using the example program built to an iPad Air 2:

Add annotation 1 (Text)
Add annotation 2 (Line)
Add annotation 3 (Highlight)
Click undo (both annotations 2 and 3 are undone)
Click "Back"
Click "Show Full PDF Viewer" (annotations 1 and 3 are visible?)

Can someone look into this...

* The actual annotation types don't seem to matter, it more an order of operations issue.

**Comment by pushchris** [comment]
Undo performs as a stack across the entire document and across all annotation types. Last item added is first item removed. In this scenario it does sound like there is a bug in that the current annotation is not written (and added to the stack) when the undo button is hit, thus removing the second to the last one. When you close the document, the pending item is added and re-appears when you re-open the document.
