### ISSUE TITLE
Undo Button Functionality?

### ISSUE THREAD

**Issue by adlartuten** [uxmstudio/UXMPDFKit#41]
is the undo button supposed to work with the pen annotation? If not is this a planned feature and could it be implemented sometime soon?

**Comment by pushchris** [comment]
The undo button should work with the pen annotation tool. Can you please post what version of the framework you are using, what version of iOS you are on, and steps to reproduce the issue.

**Comment by adlartuten** [comment]
Turns out the framework was just out of date, thanks for the help!
