### ISSUE TITLE
Load PDFViewcontroller in my UIViewController

### ISSUE THREAD

**Issue by ahmedTaalab** [uxmstudio/UXMPDFKit#48]
I'm trying to put PDFViewController in my custom view "not PUSH VIEW"
to can add custom toolBar buttons on it.
So can you advise me how can I put this controller in my custom view?

## Your Environment
<!— Include as many relevant details about the environment you experienced the bug in —>
* iOS Version:
* Xcode Version:
* Swift Version:

**Comment by pushchris** [comment]
You cannot use the PDFViewController in that way. It is a pre-built controller for use in a stand-alone fashion that is built using individual purpose blocks (annotations, etc). If you would like to incorporate things into your own view you will have to build it all from scratch. Please look at how PDFViewController functions and utilize portions of its code to accomplish what you want.
