### ISSUE TITLE
Toggle visibility of individual annotations for PDFViewController

### ISSUE THREAD

**Issue by bentacles** [uxmstudio/UXMPDFKit#49]
<!— Provide a general summary of the issue in the Title above —>
I want to restrict the highlight and text annotations inside the PDFViewController while allowing the pen annotation.

## Expected Behaviour
Add boolean values to controller the buttons for each annotation inside PDFViewController. i.e. instead of having a catch-all `allowsAnnotations`,  have 

- `allowHighlighterAnnotation`
- `allowPenAnnotation`
- `allowTextAnnotation`

These booleans would be used inside the function `fileprivate func rightBarButtons()` so that the buttons would not be appended in the navigation.

## Current Behaviour
A single boolean value for `allowsAnnotations` for the PDFViewController

**Comment by pushchris** [comment]
@bentacles thanks for proposing this. A better long term solution would be to pass an array of enums of the types of annotations you want to appear (or something similar). Currently there are only three types, but this will be changing in the nearish future. If you want to submit a pull-request to support this feel free, else it might be a little bit before I get around to integrating this. Thanks!

**Comment by bentacles** [comment]
Thanks for the changes.

I have a problem if I wanted to have different text or images inside those buttons.  
I could create my own MyAnnotationController that inherits from PDFAnnotationController.  Then define MyAnnotationController.buttons. 

The problem is most of the access levels are internal inside PDFAnnotationController.  Also I can't set my own AnnotationController inside PDFViewController.

I would also like to define my own buttons in rightBarButtons but it's fileprivate function.

**Comment by pushchris** [comment]
@bentacles if you take a peek at the develop branch you will see that there is a new version coming that opens up annotations considerably and allows you to change buttons, etc. Originally the PDFViewController was meant to be more of a reference than something to be extended, but as more and more people such as yourself have been using it directly and wanting customizability that is changing
