### ISSUE TITLE
Disable PDF sharing, is it possible ?

### ISSUE THREAD

**Issue by JimmyYezeguelian** [uxmstudio/UXMPDFKit#5]
Hi,

I just wondering if I can disable the PDF sharing. Is there an option or other ?

Thanks you by the advance.

**Comment by pushchris** [comment]
@JimmyYezeguelian take a look at the latest commit / release. It now has a boolean ```allowsSharing``` which will let you turn sharing on and off automatically.

**Comment by JimmyYezeguelian** [comment]
Thanks for this quick fix 👍
