### ISSUE TITLE
Extending the annotations

### ISSUE THREAD

**Issue by jorritsmit** [uxmstudio/UXMPDFKit#56]
Hi,

I am trying to extend the annotations with one of my own.  However, to do this i need to subclass pdfviewcontroller and annotationcontroller and point to the new annotationcontroller in the new pdfviewcontroller. This is not possible because of access levels:

`lazy var annotationController: PDFAnnotationController = PDFAnnotationController(document: self.document, delegate: self)`    

both document and annotationController have access level internal. Do i need to find a new route or am i doing something wrong here? It's my first time coding for ios, so it could well be :)

Thanks for your time

**Comment by pushchris** [comment]
@jorritsmit at this point I would recommend you look at the [develop](https://github.com/uxmstudio/UXMPDFKit/tree/develop) branch for dealing with custom annotation types. The entire stack is being redeveloped to be less memory hungry and allow for greater extensibility. You'll find there is a new initializer that allows for utilizing your own ```PDFAnnotationController``` as well as added ability to provide your own buttons for use in the menu bar. The branch will be merged into master within the next couple of weeks here so there should not be many if any changes that will break whatever you develop.

**Comment by jorritsmit** [comment]
wow thanks a lot, will definitely look at that. keep up the great work!
