### ISSUE TITLE
Need a full example in readme

### ISSUE THREAD

**Issue by neetrath** [uxmstudio/UXMPDFKit#57]
I'm a newbie in Swift and I don't know how to save the pdf file.

I use pod try UXMPDFKit to see how to save the pdf but can't see where is the code to save the pdf file.

**Comment by pushchris** [comment]
@neetrath saving a PDF is part of PDFViewController that you can see in the example project that can be downloaded from Github. If you want to be able to save a PDF from code you will need to create your own subclass of the controller. You can refer to [this line](https://github.com/uxmstudio/UXMPDFKit/blob/master/Pod/Classes/Renderer/PDFViewController.swift#L225) to see how it is done internally.
