### ISSUE TITLE
Trying to search inside the PDF?

### ISSUE THREAD

**Issue by hemangshah** [uxmstudio/UXMPDFKit#58]
Anything in your code to start from?

**Comment by pushchris** [comment]
There is currently no way to extract data from a PDF for searching purposes. It is on the radar for future additions, but not anytime soon. I would recommend you check out another pod for searching abilities: [https://github.com/KurtCode/PDFKitten](PDFKitten)

**Comment by hemangshah** [comment]
Thanks, I knew about this. It's purely written in Objective-C and there's no good solution for Swift.

**Comment by prasen-ftech** [comment]
@hemangshah , there is a good solution https://github.com/tzshlyt/iOS11-PDFKit-Example

**Comment by prasen-ftech** [comment]
@pushchris , can you include the search capability to your existing library. Similar to https://github.com/tzshlyt/iOS11-PDFKit-Example
