### ISSUE TITLE
Open viewer at specific page

### ISSUE THREAD

**Issue by rbresjer** [uxmstudio/UXMPDFKit#6]
Hi Chris,

First of all: great work! Thanks for this great PDF viewer.

If I set the PDFDocument to a specific page before initializing the PDFViewController with it, the page scrubber is shown at the correct page, but the document viewer isn't:
```swift
let document = PDFDocument(filePath: pdfFilePath)
document.currentPage = 33
let pdfVc = PDFViewController(document: document)
```

Is this an easy fix?

Best regards,
Rutger

**Comment by pushchris** [comment]
@rbresjer please see the latest commit. Your code should now function as you expected it to. Please make sure your page number is not greater than the total number of pages in the document though. Currently working on a way to ensure going outside bounds won't cause a crash.

**Comment by rbresjer** [comment]
Great, thanks for the (extremely) quick fix! 👍
