### ISSUE TITLE
Changing colour ?

### ISSUE THREAD

**Issue by doudmas** [uxmstudio/UXMPDFKit#62]
Hello, Thanks for this great library !
I have a question about colours, is it possible to change it (pen or/and text) ?
I would like doing a "undo" programmatically as well (I have a custom view to choose between different actions).
I don't want to change your code to keep this repository up-to-date in my project.
Thanks !

* iOS Version: 10.2.1
* Xcode Version: 8.3.3
* Swift Version: 3

**Comment by pushchris** [comment]
@doudmas please look at the latest build. Those properties and functions have been made public so that you can access them and change them at will
