### ISSUE TITLE
Load pdf from remote url

### ISSUE THREAD

**Issue by gsolanki1509** [uxmstudio/UXMPDFKit#68]
<!— Provide a general summary of the issue in the Title above —>

## Expected Behavior

Want to load pdf from remote url rather than from local.

Please help.

**Comment by pushchris** [comment]
This framework does not support any networking capability. In order to accomplish this you will need to incorporate something like [Alamofire](https://github.com/Alamofire/Alamofire) into your project and then open the downloaded file with this framework
