### ISSUE TITLE
self.presentingViewController != nil

### ISSUE THREAD

**Issue by hslightnin** [uxmstudio/UXMPDFKit#9]
func isModal() this is returning true because self.presentingViewController isn't nil.

im presenting like in the example
`           
                self.navigationController?.pushViewController(pdf, animated: true)`

**Comment by pushchris** [comment]
@hslightnin please check the latest update. I've moved the push/present logic to the developer side as a boolean `isPresentingInModal` instead of automatically calculating it. There were too many edge cases when trying to handle it automatically.
